apply plugin: 'java-library'

targetCompatibility = 1.8
sourceCompatibility = 1.8

repositories {
    mavenCentral()
}


def generateBuild = tasks.register("generateBuild") {
    def outputDir = layout.buildDirectory.dir("generated/sources/build/main/java")
    outputs.dir(outputDir)

    doLast {
        def file = new File(outputDir.get().asFile, "com/africastalking/Build.java")
        file.parentFile.mkdirs()
        file.text = """
        package com.africastalking;
        public final class Build {
            public static final String VERSION = $project.version;
        }
        """
    }
}

sourceSets {
    main {
        java {
            srcDir(generateBuild)
        }
    }
}

dependencies {

    api 'com.squareup.retrofit2:retrofit:2.1.0'
    api 'com.squareup.retrofit2:converter-scalars:2.1.0'
    api 'com.squareup.retrofit2:converter-gson:2.1.0'
    api 'com.squareup.okhttp3:logging-interceptor:3.5.0'
    api 'org.valid4j:valid4j:0.5.0'


    testImplementation group: 'junit', name: 'junit', version: '4.11'
}
